import os
import sys
import time
blue='\033[36m'
rang='\033[34m'
print(f"{blue} ")
os.system("clear")
print ("         Script By")
red='\033[31m'
print(f"{red} ")
print ("               _   _            ____                       _    __")
print (" _ __ ___     (_) (_)          / ___|   __ _   ___   ___  (_)  / _|   ___ _ __")
print ("| '_ ` _ \    | | | |  _____  | |      / _` | / __| / __| | | | |_   / _ \ '__|")
print ("| | | | | |   | | | | |_____| | |___  | (_| | \__ \ \__ \ | | |  _| |  __/ |")
print ("|_| |_| |_|  _/ | |_|          \____|  \__,_| |___/ |___/ |_| |_|    \___|_|")
print("      |__/")
time.sleep(5.3)
green='\033[32m'
print(f"{green} ")
time.sleep(2.7)
print("                   ID RUBIKA @SHUBADEHBAZ IM MOJTABA CASSIFER")
print ("                         ID telegram @Creator_Typeri")
print(f"{green} ")
time.sleep(2)
print("__________")
time.sleep(0.7)
print("#_________")
time.sleep(0.6)
print("##________")
time.sleep(0.5)
print("###_______")
time.sleep(0.4)
print("####______")
time.sleep(0.3)
print("#####_____")
time.sleep(0.2)
print("######____")
time.sleep(0.1)
print("#######___")
time.sleep(0.5)
print("########__")
time.sleep(0.1)
print("#########_")
time.sleep(0.1)
print("##########")
select = int(input(" type 1 = update code  ☘️and☘️ type 2 = Get Code: "))
update = input("type 1 for update Script & type 2 for get Code☘️: ")
if update == "1":
        os.system("cd")
        os.system("rm -rf /data/data/com.termux/files/home/Filtering-Rubika")
        os.system("git clone https://github.com/C4ssif3r/Filtering")
        os.system("cd $HOME")
        os.system("cd Filtering")
        os.system("chmod 777 Filtering-Rubika.py")
        os.system("python Filtering-Rubika.py")
code = (input(" type : 2 for get code :  "))
time.sleep(3.0)
print(f"{red} ")
if code == "2": print ("code 👉 👉   yttk_15570  👈 👈For Update type 1 -")
time.sleep(3.0)
print(f"{blue}" )
print (" Baraye Estefade Az code dar kanal rubika' man ozv shin-!🌟 -! ")
time.sleep(3.0)
print(f"{rang}" )
print (" Kanal rubikam = @Cassif3r")
time.sleep(3.0)
print (" Bye Bye My Friend :)💔")

